const express = require("express");
const router = express.Router();
const {createSoundGroup, assignSoundGroup, skipImage, soundGroupGallery, soundGroupGalleryByType, getTrainingVideo, soundGroupGalleryStatus, getSoundGroupList, checkStatusOfImagesCompletedForSoundGroup, deleteSoundGroup, deleteAllEmptySoundGroup} = require("../controllers/soundGroupController");
const validateObjectIds = require("../middlewares/validateObjectIdsMiddleware");
router.post("/createSoundGroup", validateObjectIds(["userId", "imageId"]), createSoundGroup);
router.post("/assignSoundGroup", validateObjectIds(["userId", "imageId", "soundGroupId"]), assignSoundGroup);
router.post("/skipSoundGroup", validateObjectIds(["userId", "imageId", "skip"]), skipImage);
router.get("/soundGroupGallery", validateObjectIds(["userId"]), soundGroupGallery);
router.get("/soundGroupGalleryByType", validateObjectIds(["userId", "soundGroupId"]), soundGroupGalleryByType);
router.delete("/deleteSoundGroup", validateObjectIds(["userId", "soundGroupId"]), deleteSoundGroup);
router.get("/getTrainingVideo", getTrainingVideo);
router.get("/getSoundGroups", validateObjectIds(["userId"]), getSoundGroupList);
router.get("/getCompletionStatusForSoundGroup", validateObjectIds(["userId"]), checkStatusOfImagesCompletedForSoundGroup);
router.delete("/deleteAllEmptySoundGroup", validateObjectIds(["userId"]), deleteAllEmptySoundGroup);
module.exports = router;
